In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [2]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [3]:
l=SVC(C=1e5,kernel="linear")
l.fit(X,y)

SVC(C=100000.0, kernel='linear')

In [4]:
print("w=",l.coef_)
print("b=",l.intercept_)
print("Indices of support vectors=",l.support_)
print("Support vectors=",l.support_vectors_)
print("No. of support vectors from each class=",l.n_support_)
print("coefficient of support vectors in decision function=",np.abs(l.dual_coef_))

w= [[ 0.25 -0.25]]
b= [-0.75]
Indices of support vectors= [2 3]
Support vectors= [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class= [1 1]
coefficient of support vectors in decision function= [[0.0625 0.0625]]


In [6]:
import pandas as pd
data=pd.read_csv("heart.csv")
data.head()
x=data.drop("target",axis=1)
y=data.target

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [8]:
linear=svm.SVC(kernel="linear")
linear.fit(x_train,y_train)

print(linear.support_vectors_)

[[57.  1.  2. ...  1.  1.  3.]
 [39.  1.  0. ...  1.  0.  3.]
 [52.  1.  0. ...  2.  1.  2.]
 ...
 [58.  1.  1. ...  1.  4.  3.]
 [54.  1.  1. ...  2.  0.  3.]
 [61.  1.  2. ...  1.  0.  2.]]


In [9]:
print(linear.n_support_)
y_pred=linear.predict(x_test)

[40 42]


In [10]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8241758241758241


In [11]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[32 11]
 [ 5 43]]


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.74      0.80        43
           1       0.80      0.90      0.84        48

    accuracy                           0.82        91
   macro avg       0.83      0.82      0.82        91
weighted avg       0.83      0.82      0.82        91



In [13]:
model1=SVC(kernel="sigmoid")
model2=SVC(kernel="poly")
model3=SVC(kernel="rbf")

In [14]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [15]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [16]:
print("prediction by model1",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred1))

prediction by model1 0.5274725274725275
prediction by model2 0.6483516483516484
prediction by model3 0.5274725274725275
